---
# tasks file for roles

  - name: update cache
    command: apt-get update

  - name: ensure repository key is installed
    apt_key:
      id: "58118E89F3A912897C070ADBF76221572C52609D"
      keyserver: "hkp://p80.pool.sks-keyservers.net:80"
      state: present

  - name: ensure docker registry is available
    apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present

  - name: update cache
    command: apt-get update

  - name: install docker
    command: apt-get install -y docker-engine


  - name: add user mod
    command:  usermod -aG docker ubuntu