#- name: dependency provisioning
#  hosts: jenkins
#  become: yes
#  become_method: sudo
#  gather_facts: false
#  tasks:
#    - name: install python2
#      raw: sudo apt-get -y install python-simplejson


- name: Install nginx
  hosts: Proxy
  become: yes
  become_method: sudo
  roles:
    - role: nginx
    
#- name: Install jenkins
#  hosts: jenkins
#  become: yes
#  become_method: sudo
#  roles:
#    - role: jenkins
    
